name: Actions
on: [push]
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: IGNORE_VERSION_CHECK=TRUE python3 scripts/package.py
